"""
=========================================================
FlowForge - AI Schemas
=========================================================

WHY THIS FILE EXISTS
--------------------
"Schemas" (using the Pydantic library) are blueprints for the data 
that comes INTO our API and goes OUT of our API.

FastAPI uses these schemas to automatically:
1. Validate the data (make sure a string is a string, a number is a number).
2. Generate automatic documentation (Swagger UI).
3. Return clean, predictable JSON to the frontend.

In this file, we define what the Frontend sends to the AI (AiChatRequest)
and what the AI sends back to the Frontend (AiChatResponse).
"""

# =====================================================
# Imports
# =====================================================

# 'BaseModel' is the core class from Pydantic. All our schemas will inherit from this.
# 'Field' lets us add extra rules to our data (like "this text must be at least 1 character").
from pydantic import BaseModel, Field

# 'List' from the 'typing' library helps us specify that a variable is a list of a certain type.
from typing import List


# =====================================================
# Request Schema (Input from Frontend)
# =====================================================

# We create a new schema named 'AiChatRequest'.
# It inherits from 'BaseModel', meaning Pydantic will process it.
class AiChatRequest(BaseModel):
    """
    This is what the React frontend will send to our FastAPI backend
    when the user types a message in the chat box.
    """
    
    # We define a field called 'user_message'.
    # ': str' means it MUST be a string (text).
    # 'Field(...)' means this field is REQUIRED (the '...' is Python's way of saying "required").
    # 'min_length=1' ensures the user can't send an empty message.
    # 'max_length=1000' ensures they don't send a giant essay that crashes the AI.
    user_message: str = Field(..., min_length=1, max_length=1000)

    # OPTIONAL: The ID of the board the user is currently viewing.
    # When provided, the AI will scope its search to the project that board belongs to.
    # When None (e.g., chatbot opened from the Dashboard), it searches all user projects.
    board_id: int | None = Field(None, description="The current board ID for context-aware search.")


# =====================================================
# Response Schema (Output to Frontend)
# =====================================================

# We create a new schema named 'AiChatResponse'.
class AiChatResponse(BaseModel):
    """
    This is what our FastAPI backend will send BACK to the React frontend
    after Gemini generates the answer.
    """
    
    # 'response' will hold the actual text answer generated by Gemini.
    # ': str' means it will be text.
    response: str
    
    # 'sources' will hold a list of the Task IDs that Gemini used to answer the question.
    # We send these back so the frontend can display clickable links to the tasks!
    # ': List[int]' means it MUST be a list of integers (whole numbers).
    sources: List[int]
